version: '3.3'

services:
  data-base:
    container_name: data-base
    image: mysql:8.0.20
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --sql_mode="" --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'OCMSoliServer'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  solicitudes:
    container_name: solicitudes
    build:
      context: ./
    ports:
      - '80:8081'
    environment:
      - DATABASE_URL=mysql://root:root@data-base/OCMSoliServer # TODO Cambiar despues el usuario y contraseña
      - NODE_ENV=prod
    depends_on:
      - data-base
    links:
      - data-base
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - data-base
    environment:
      PMA_HOST: data-base
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
# Names our volume
volumes:
  my-db:
